// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    $.fn.kanji = function(options) {
      var opts;
      return opts = $.extend({}, $.fn.kanji.defaults, options);
    };
    return $.fn.kanji.defaults = {
      a: 10
    };
  });

}).call(this);
